apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app-deployment
  labels:
    app: train-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-app
  template:
    metadata:
      labels:
        app: train-app
    spec:
      containers:
      - name: train-app
        image: ${DOCKER_IMAGE_NAME}:${BUILD_ID}
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: train-app-service
spec:
  selector:
    app: train-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
